language: python
python:
    - "3.5"
install:
    - pip install -r ./requirements/tests.txt
    - pip install coveralls
    - pip install -r ./requirements/docs.txt
script:
    - make test
    - make docs
after_success:
    coveralls
